version: "3"
services:
    app:
        build: .
        command: yarn start:dev
        ports:
            - "3000:3000"
        volumes: 
            - .:/usr/app
    mongo:
        image: mongo
        restart: always
        environment: 
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example